### ISSUE TITLE
populus doesn't like newer version of solc

### ISSUE THREAD

**Issue by Netherdrake** [ethereum/populus#387]
```
~ % solc --version
solc, the solidity compiler commandline interface
Version: 0.4.18+commit.9cf6e910.Darwin.appleclang
~ % pip show populus
Name: populus
Version: 1.11.2
```

```
% populus compile
Traceback (most recent call last):
  File "/Users/user/anaconda/bin/populus", line 11, in <module>
    sys.exit(main())
  File "/Users/user/anaconda/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/user/anaconda/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/user/anaconda/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/user/anaconda/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/user/anaconda/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/user/anaconda/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/user/anaconda/lib/python3.6/site-packages/populus/cli/compile_cmd.py", line 29, in compile_cmd
    compile_project(project, watch)
  File "/Users/user/anaconda/lib/python3.6/site-packages/populus/api/compile_contracts.py", line 18, in compile_project
    _, compiled_contracts = compile_project_contracts(project)
  File "/Users/user/anaconda/lib/python3.6/site-packages/populus/compilation/__init__.py", line 51, in compile_project_contracts
    compiler_backend = project.get_compiler_backend()
  File "/Users/user/anaconda/lib/python3.6/site-packages/populus/project.py", line 314, in get_compiler_backend
    return compilation_config.backend
  File "/Users/user/anaconda/lib/python3.6/site-packages/populus/config/compiler.py", line 53, in backend
    return self.backend_class(self.backend_settings)
  File "/Users/user/anaconda/lib/python3.6/site-packages/populus/compilation/backends/solc_combined_json.py", line 135, in __init__
    "The 'SolcCombinedJSONBackend can only be used with solc "
OSError: The 'SolcCombinedJSONBackend can only be used with solc versions <=0.4.8.  The SolcStandardJSONBackend should be used for all versions >=0.4.9
```

![catgif](https://user-images.githubusercontent.com/3516903/33341318-eedebfea-d47e-11e7-8b77-e1df4ab59488.gif)

**Comment by Netherdrake** [comment]
I tried switching to `SolcStandardJSONBackend` in my `project.json`, and now it compiles just fine.
