### ISSUE TITLE
"populus compile --watch" fails

### ISSUE THREAD

**Issue by JanKalin** [ethereum/populus#418]
* Populus Version: 2.2.0
* OS: Debian64

```
jank@scu:~/snapchain/test$ populus compile --watch
> Found 1 contract source files
  - contracts/Greeter.sol
> Compiled 1 contracts
  - contracts/Greeter.sol:Greeter
> Wrote compiled assets to: build/contracts.json
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
TypeError: watch_project_contracts() missing 1 required positional argument: 'compiler_settings'
```

![image](https://user-images.githubusercontent.com/18305372/34260688-034e8ac4-e667-11e7-8bba-8ffc04c420da.png)

**Comment by introom** [comment]
confirm this issue.
