### ISSUE TITLE
Install with python3.6 setup.py install fails.

### ISSUE THREAD

**Issue by postables** [ethereum/populus#432]
```sudo python3.6 setup.py install
[sudo] password for solidity: 
running install
running bdist_egg
running egg_info
writing populus.egg-info/PKG-INFO
writing dependency_links to populus.egg-info/dependency_links.txt
writing entry points to populus.egg-info/entry_points.txt
writing requirements to populus.egg-info/requires.txt
writing top-level names to populus.egg-info/top_level.txt
INFO:root:Generating grammar tables from /usr/lib/python3.6/lib2to3/Grammar.txt
INFO:root:Generating grammar tables from /usr/lib/python3.6/lib2to3/PatternGrammar.txt
file populus.py (for module populus) not found
reading manifest file 'populus.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'VERSION'
warning: no files found matching 'requirements.txt'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
writing manifest file 'populus.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
file populus.py (for module populus) not found
file populus.py (for module populus) not found
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/populus
creating build/bdist.linux-x86_64/egg/populus/config
copying build/lib/populus/config/base.py -> build/bdist.linux-x86_64/egg/populus/config
copying build/lib/populus/config/chain.py -> build/bdist.linux-x86_64/egg/populus/config
copying build/lib/populus/config/versions.py -> build/bdist.linux-x86_64/egg/populus/config
copying build/lib/populus/config/backend.py -> build/bdist.linux-x86_64/egg/populus/config
copying build/lib/populus/config/web3.py -> build/bdist.linux-x86_64/egg/populus/config
copying build/lib/populus/config/loading.py -> build/bdist.linux-x86_64/egg/populus/config
copying build/lib/populus/config/__init__.py -> build/bdist.linux-x86_64/egg/populus/config
creating build/bdist.linux-x86_64/egg/populus/config/upgrade
copying build/lib/populus/config/upgrade/v3.py -> build/bdist.linux-x86_64/egg/populus/config/upgrade
copying build/lib/populus/config/upgrade/v5.py -> build/bdist.linux-x86_64/egg/populus/config/upgrade
copying build/lib/populus/config/upgrade/v2.py -> build/bdist.linux-x86_64/egg/populus/config/upgrade
copying build/lib/populus/config/upgrade/v7.py -> build/bdist.linux-x86_64/egg/populus/config/upgrade
copying build/lib/populus/config/upgrade/v1.py -> build/bdist.linux-x86_64/egg/populus/config/upgrade
copying build/lib/populus/config/upgrade/v4.py -> build/bdist.linux-x86_64/egg/populus/config/upgrade
copying build/lib/populus/config/upgrade/__init__.py -> build/bdist.linux-x86_64/egg/populus/config/upgrade
copying build/lib/populus/config/upgrade/v6.py -> build/bdist.linux-x86_64/egg/populus/config/upgrade
copying build/lib/populus/config/helpers.py -> build/bdist.linux-x86_64/egg/populus/config
copying build/lib/populus/config/compiler.py -> build/bdist.linux-x86_64/egg/populus/config
copying build/lib/populus/config/validation.py -> build/bdist.linux-x86_64/egg/populus/config
copying build/lib/populus/config/defaults.py -> build/bdist.linux-x86_64/egg/populus/config
copying build/lib/populus/project.py -> build/bdist.linux-x86_64/egg/populus
creating build/bdist.linux-x86_64/egg/populus/contracts
copying build/lib/populus/contracts/provider.py -> build/bdist.linux-x86_64/egg/populus/contracts
copying build/lib/populus/contracts/registrar.py -> build/bdist.linux-x86_64/egg/populus/contracts
copying build/lib/populus/contracts/exceptions.py -> build/bdist.linux-x86_64/egg/populus/contracts
copying build/lib/populus/contracts/__init__.py -> build/bdist.linux-x86_64/egg/populus/contracts
copying build/lib/populus/contracts/contract.py -> build/bdist.linux-x86_64/egg/populus/contracts
creating build/bdist.linux-x86_64/egg/populus/contracts/backends
copying build/lib/populus/contracts/backends/project.py -> build/bdist.linux-x86_64/egg/populus/contracts/backends
copying build/lib/populus/contracts/backends/base.py -> build/bdist.linux-x86_64/egg/populus/contracts/backends
copying build/lib/populus/contracts/backends/filesystem.py -> build/bdist.linux-x86_64/egg/populus/contracts/backends
copying build/lib/populus/contracts/backends/testing.py -> build/bdist.linux-x86_64/egg/populus/contracts/backends
copying build/lib/populus/contracts/backends/memory.py -> build/bdist.linux-x86_64/egg/populus/contracts/backends
copying build/lib/populus/contracts/backends/__init__.py -> build/bdist.linux-x86_64/egg/populus/contracts/backends
copying build/lib/populus/plugin.py -> build/bdist.linux-x86_64/egg/populus
copying build/lib/populus/wait.py -> build/bdist.linux-x86_64/egg/populus
creating build/bdist.linux-x86_64/egg/populus/api
copying build/lib/populus/api/project.py -> build/bdist.linux-x86_64/egg/populus/api
copying build/lib/populus/api/compile_contracts.py -> build/bdist.linux-x86_64/egg/populus/api
copying build/lib/populus/api/upgrade.py -> build/bdist.linux-x86_64/egg/populus/api
copying build/lib/populus/api/utils.py -> build/bdist.linux-x86_64/egg/populus/api
copying build/lib/populus/api/__init__.py -> build/bdist.linux-x86_64/egg/populus/api
copying build/lib/populus/api/deploy.py -> build/bdist.linux-x86_64/egg/populus/api
creating build/bdist.linux-x86_64/egg/populus/chain
copying build/lib/populus/chain/testrpc.py -> build/bdist.linux-x86_64/egg/populus/chain
copying build/lib/populus/chain/base.py -> build/bdist.linux-x86_64/egg/populus/chain
copying build/lib/populus/chain/external.py -> build/bdist.linux-x86_64/egg/populus/chain
copying build/lib/populus/chain/geth.py -> build/bdist.linux-x86_64/egg/populus/chain
copying build/lib/populus/chain/__init__.py -> build/bdist.linux-x86_64/egg/populus/chain
copying build/lib/populus/chain/tester.py -> build/bdist.linux-x86_64/egg/populus/chain
creating build/bdist.linux-x86_64/egg/populus/utils
copying build/lib/populus/utils/cli.py -> build/bdist.linux-x86_64/egg/populus/utils
copying build/lib/populus/utils/formatting.py -> build/bdist.linux-x86_64/egg/populus/utils
copying build/lib/populus/utils/chains.py -> build/bdist.linux-x86_64/egg/populus/utils
copying build/lib/populus/utils/types.py -> build/bdist.linux-x86_64/egg/populus/utils
copying build/lib/populus/utils/networking.py -> build/bdist.linux-x86_64/egg/populus/utils
copying build/lib/populus/utils/filesystem.py -> build/bdist.linux-x86_64/egg/populus/utils
copying build/lib/populus/utils/accounts.py -> build/bdist.linux-x86_64/egg/populus/utils
copying build/lib/populus/utils/testing.py -> build/bdist.linux-x86_64/egg/populus/utils
copying build/lib/populus/utils/contracts.py -> build/bdist.linux-x86_64/egg/populus/utils
copying build/lib/populus/utils/geth.py -> build/bdist.linux-x86_64/egg/populus/utils
copying build/lib/populus/utils/string.py -> build/bdist.linux-x86_64/egg/populus/utils
copying build/lib/populus/utils/json.py -> build/bdist.linux-x86_64/egg/populus/utils
copying build/lib/populus/utils/wait.py -> build/bdist.linux-x86_64/egg/populus/utils
creating build/bdist.linux-x86_64/egg/populus/utils/six
copying build/lib/populus/utils/six/six_py3.py -> build/bdist.linux-x86_64/egg/populus/utils/six
copying build/lib/populus/utils/six/six_py2.py -> build/bdist.linux-x86_64/egg/populus/utils/six
copying build/lib/populus/utils/six/__init__.py -> build/bdist.linux-x86_64/egg/populus/utils/six
copying build/lib/populus/utils/linking.py -> build/bdist.linux-x86_64/egg/populus/utils
copying build/lib/populus/utils/mappings.py -> build/bdist.linux-x86_64/egg/populus/utils
copying build/lib/populus/utils/compile.py -> build/bdist.linux-x86_64/egg/populus/utils
copying build/lib/populus/utils/empty.py -> build/bdist.linux-x86_64/egg/populus/utils
copying build/lib/populus/utils/__init__.py -> build/bdist.linux-x86_64/egg/populus/utils
copying build/lib/populus/utils/logging.py -> build/bdist.linux-x86_64/egg/populus/utils
copying build/lib/populus/utils/functional.py -> build/bdist.linux-x86_64/egg/populus/utils
copying build/lib/populus/utils/observers.py -> build/bdist.linux-x86_64/egg/populus/utils
copying build/lib/populus/utils/proc.py -> build/bdist.linux-x86_64/egg/populus/utils
copying build/lib/populus/utils/base58.py -> build/bdist.linux-x86_64/egg/populus/utils
copying build/lib/populus/utils/module_loading.py -> build/bdist.linux-x86_64/egg/populus/utils
copying build/lib/populus/utils/deploy.py -> build/bdist.linux-x86_64/egg/populus/utils
copying build/lib/populus/exceptions.py -> build/bdist.linux-x86_64/egg/populus
copying build/lib/populus/__init__.py -> build/bdist.linux-x86_64/egg/populus
creating build/bdist.linux-x86_64/egg/populus/assets
copying build/lib/populus/assets/defaults.v6.config.json -> build/bdist.linux-x86_64/egg/populus/assets
copying build/lib/populus/assets/defaults.v4.config.json -> build/bdist.linux-x86_64/egg/populus/assets
copying build/lib/populus/assets/config.v7.schema.json -> build/bdist.linux-x86_64/egg/populus/assets
copying build/lib/populus/assets/config.v2.schema.json -> build/bdist.linux-x86_64/egg/populus/assets
copying build/lib/populus/assets/config.v1.schema.json -> build/bdist.linux-x86_64/egg/populus/assets
copying build/lib/populus/assets/defaults.v3.config.json -> build/bdist.linux-x86_64/egg/populus/assets
copying build/lib/populus/assets/defaults.v7.config.json -> build/bdist.linux-x86_64/egg/populus/assets
copying build/lib/populus/assets/config.v5.schema.json -> build/bdist.linux-x86_64/egg/populus/assets
copying build/lib/populus/assets/config.v6.schema.json -> build/bdist.linux-x86_64/egg/populus/assets
copying build/lib/populus/assets/defaults.v8.config.json -> build/bdist.linux-x86_64/egg/populus/assets
copying build/lib/populus/assets/config.v3.schema.json -> build/bdist.linux-x86_64/egg/populus/assets
copying build/lib/populus/assets/config.v4.schema.json -> build/bdist.linux-x86_64/egg/populus/assets
copying build/lib/populus/assets/defaults.user.v7.config.json -> build/bdist.linux-x86_64/egg/populus/assets
copying build/lib/populus/assets/config.v8.schema.json -> build/bdist.linux-x86_64/egg/populus/assets
copying build/lib/populus/assets/defaults.v1.config.json -> build/bdist.linux-x86_64/egg/populus/assets
copying build/lib/populus/assets/defaults.v2.config.json -> build/bdist.linux-x86_64/egg/populus/assets
copying build/lib/populus/assets/defaults.v5.config.json -> build/bdist.linux-x86_64/egg/populus/assets
copying build/lib/populus/assets/contract-data.v1.schema.json -> build/bdist.linux-x86_64/egg/populus/assets
copying build/lib/populus/assets/defaults.user.v8.config.json -> build/bdist.linux-x86_64/egg/populus/assets
copying build/lib/populus/assets/test_greeter.py -> build/bdist.linux-x86_64/egg/populus/assets
copying build/lib/populus/assets/Greeter.sol -> build/bdist.linux-x86_64/egg/populus/assets
creating build/bdist.linux-x86_64/egg/populus/cli
copying build/lib/populus/cli/config_cmd.py -> build/bdist.linux-x86_64/egg/populus/cli
copying build/lib/populus/cli/deploy_cmd.py -> build/bdist.linux-x86_64/egg/populus/cli
copying build/lib/populus/cli/init_cmd.py -> build/bdist.linux-x86_64/egg/populus/cli
copying build/lib/populus/cli/main.py -> build/bdist.linux-x86_64/egg/populus/cli
copying build/lib/populus/cli/compile_cmd.py -> build/bdist.linux-x86_64/egg/populus/cli
copying build/lib/populus/cli/upgrade_cmd.py -> build/bdist.linux-x86_64/egg/populus/cli
copying build/lib/populus/cli/__init__.py -> build/bdist.linux-x86_64/egg/populus/cli
copying build/lib/populus/cli/chain_cmd.py -> build/bdist.linux-x86_64/egg/populus/cli
creating build/bdist.linux-x86_64/egg/populus/compilation
copying build/lib/populus/compilation/__init__.py -> build/bdist.linux-x86_64/egg/populus/compilation
creating build/bdist.linux-x86_64/egg/populus/compilation/backends
copying build/lib/populus/compilation/backends/base.py -> build/bdist.linux-x86_64/egg/populus/compilation/backends
copying build/lib/populus/compilation/backends/viper.py -> build/bdist.linux-x86_64/egg/populus/compilation/backends
copying build/lib/populus/compilation/backends/solc_combined_json.py -> build/bdist.linux-x86_64/egg/populus/compilation/backends
copying build/lib/populus/compilation/backends/solc_auto.py -> build/bdist.linux-x86_64/egg/populus/compilation/backends
copying build/lib/populus/compilation/backends/solc_standard_json.py -> build/bdist.linux-x86_64/egg/populus/compilation/backends
copying build/lib/populus/compilation/backends/__init__.py -> build/bdist.linux-x86_64/egg/populus/compilation/backends
byte-compiling build/bdist.linux-x86_64/egg/populus/config/base.py to base.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/config/chain.py to chain.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/config/versions.py to versions.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/config/backend.py to backend.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/config/web3.py to web3.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/config/loading.py to loading.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/config/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/config/upgrade/v3.py to v3.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/config/upgrade/v5.py to v5.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/config/upgrade/v2.py to v2.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/config/upgrade/v7.py to v7.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/config/upgrade/v1.py to v1.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/config/upgrade/v4.py to v4.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/config/upgrade/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/config/upgrade/v6.py to v6.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/config/helpers.py to helpers.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/config/compiler.py to compiler.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/config/validation.py to validation.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/config/defaults.py to defaults.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/project.py to project.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/contracts/provider.py to provider.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/contracts/registrar.py to registrar.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/contracts/exceptions.py to exceptions.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/contracts/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/contracts/contract.py to contract.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/contracts/backends/project.py to project.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/contracts/backends/base.py to base.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/contracts/backends/filesystem.py to filesystem.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/contracts/backends/testing.py to testing.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/contracts/backends/memory.py to memory.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/contracts/backends/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/plugin.py to plugin.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/wait.py to wait.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/api/project.py to project.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/api/compile_contracts.py to compile_contracts.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/api/upgrade.py to upgrade.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/api/utils.py to utils.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/api/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/api/deploy.py to deploy.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/chain/testrpc.py to testrpc.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/chain/base.py to base.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/chain/external.py to external.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/chain/geth.py to geth.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/chain/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/chain/tester.py to tester.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/utils/cli.py to cli.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/utils/formatting.py to formatting.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/utils/chains.py to chains.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/utils/types.py to types.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/utils/networking.py to networking.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/utils/filesystem.py to filesystem.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/utils/accounts.py to accounts.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/utils/testing.py to testing.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/utils/contracts.py to contracts.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/utils/geth.py to geth.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/utils/string.py to string.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/utils/json.py to json.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/utils/wait.py to wait.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/utils/six/six_py3.py to six_py3.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/utils/six/six_py2.py to six_py2.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/utils/six/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/utils/linking.py to linking.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/utils/mappings.py to mappings.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/utils/compile.py to compile.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/utils/empty.py to empty.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/utils/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/utils/logging.py to logging.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/utils/functional.py to functional.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/utils/observers.py to observers.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/utils/proc.py to proc.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/utils/base58.py to base58.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/utils/module_loading.py to module_loading.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/utils/deploy.py to deploy.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/exceptions.py to exceptions.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/assets/test_greeter.py to test_greeter.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/cli/config_cmd.py to config_cmd.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/cli/deploy_cmd.py to deploy_cmd.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/cli/init_cmd.py to init_cmd.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/cli/main.py to main.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/cli/compile_cmd.py to compile_cmd.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/cli/upgrade_cmd.py to upgrade_cmd.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/cli/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/cli/chain_cmd.py to chain_cmd.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/compilation/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/compilation/backends/base.py to base.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/compilation/backends/viper.py to viper.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/compilation/backends/solc_combined_json.py to solc_combined_json.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/compilation/backends/solc_auto.py to solc_auto.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/compilation/backends/solc_standard_json.py to solc_standard_json.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/populus/compilation/backends/__init__.py to __init__.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying populus.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying populus.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying populus.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying populus.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying populus.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying populus.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying populus.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/populus-2.2.0-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing populus-2.2.0-py3.6.egg
removing '/usr/local/lib/python3.6/dist-packages/populus-2.2.0-py3.6.egg' (and everything under it)
creating /usr/local/lib/python3.6/dist-packages/populus-2.2.0-py3.6.egg
Extracting populus-2.2.0-py3.6.egg to /usr/local/lib/python3.6/dist-packages
populus 2.2.0 is already the active version in easy-install.pth
Installing populus script to /usr/local/bin

Installed /usr/local/lib/python3.6/dist-packages/populus-2.2.0-py3.6.egg
Processing dependencies for populus==2.2.0
Searching for secp256k1
Reading https://pypi.python.org/simple/secp256k1/
Downloading https://pypi.python.org/packages/52/62/d7bf3829e126e517e253d2e22a63511c54bbaac34d7ddea316cde040fc49/secp256k1-0.13.2.tar.gz#md5=7bd85034357b9fdeb8456c5a60b3bf63
Best match: secp256k1 0.13.2
Processing secp256k1-0.13.2.tar.gz
Writing /tmp/easy_install-0vuhbtwb/secp256k1-0.13.2/setup.cfg
Running secp256k1-0.13.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-0vuhbtwb/secp256k1-0.13.2/egg-dist-tmp-6ot4qdw6
0.29.1
zip_safe flag not set; analyzing archive contents...

Installed /tmp/easy_install-0vuhbtwb/secp256k1-0.13.2/.eggs/pytest_runner-2.6.2-py3.6.egg
Using bundled libsecp256k1
configure.ac:20: installing 'build-aux/compile'
configure.ac:5: installing 'build-aux/config.guess'
configure.ac:5: installing 'build-aux/config.sub'
configure.ac:9: installing 'build-aux/install-sh'
configure.ac:9: installing 'build-aux/missing'
Makefile.am:3: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:3:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:3:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:3:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:3:   its definition is in aclocal's search path.
Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
autoreconf: automake failed with exit status: 1
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 158, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 49, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-0vuhbtwb/secp256k1-0.13.2/setup.py", line 295, in <module>
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 160, in run
    self.run_command('build_clib')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/tmp/easy_install-0vuhbtwb/secp256k1-0.13.2/setup.py", line 165, in run
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/easy_install-0vuhbtwb/secp256k1-0.13.2/libsecp256k1/autogen.sh']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 53, in <module>
    'Programming Language :: Python :: 3.4',
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 436, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 678, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 725, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 770, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 855, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1127, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1139, in obtain
    return installer(requirement)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 697, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 723, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 904, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1143, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1129, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 257, in run_setup
    raise
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 170, in save_modules
    saved_exc.resume()
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 145, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 158, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 49, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-0vuhbtwb/secp256k1-0.13.2/setup.py", line 295, in <module>
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 160, in run
    self.run_command('build_clib')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/tmp/easy_install-0vuhbtwb/secp256k1-0.13.2/setup.py", line 165, in run
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/easy_install-0vuhbtwb/secp256k1-0.13.2/libsecp256k1/autogen.sh']' returned non-zero exit status 1.```

**Comment by postables** [comment]
Was able to solve by installing `libtool` on ubuntu 17.10
