### ISSUE TITLE
`populus chain reset` command fails with AttributeError

### ISSUE THREAD

**Issue by mandarvaze** [ethereum/populus#451]
* Populus Version: 2.2.0

* OS: macOS Sierra

### What was wrong?

* full output of the error you received
```
Traceback (most recent call last):
  File "/Users/mandar/.pyenv/versions/py362apistar/bin/populus", line 11, in <module>
    sys.exit(main())
  File "/Users/mandar/.pyenv/versions/3.6.2/envs/py362apistar/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mandar/.pyenv/versions/3.6.2/envs/py362apistar/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/mandar/.pyenv/versions/3.6.2/envs/py362apistar/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mandar/.pyenv/versions/3.6.2/envs/py362apistar/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mandar/.pyenv/versions/3.6.2/envs/py362apistar/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mandar/.pyenv/versions/3.6.2/envs/py362apistar/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/mandar/.pyenv/versions/3.6.2/envs/py362apistar/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/mandar/.pyenv/versions/3.6.2/envs/py362apistar/lib/python3.6/site-packages/populus/cli/chain_cmd.py", line 56, in chain_reset
    project.get_blockchain_data_dir(chain_name),
AttributeError: 'Project' object has no attribute 'get_blockchain_data_dir'
```
* what command you ran

`populus chain reset test1` where test1 was created using `populus chain new test1`

* the code that caused the failure

See the stack trace above.

#### Cute Animal Picture

```

                                       /;    ;\
                                   __  \\____//
                                  /{_\_/   `'\____
                                  \___   (o)  (o  }
       _____________________________/          :--'
   ,-,'`@@@@@@@@       @@@@@@         \_    `__\
  ;:(  @@@@@@@@@        @@@             \___(o'o)
  :: )  @@@@          @@@@@@        ,'@@(  `===='
  :: : @@@@@:          @@@@         `@@@:
  :: \  @@@@@:       @@@@@@@)    (  '@@@'
  ;; /\      /`,    @@@@@@@@@\   :@@@@@)
  ::/  )    {_----------------:  :~`,~~;
 ;;'`; :   )                  :  / `; ;   
;;;; : :   ;                  :  ;  ; :
`'`' / :  :                   :  :  : :
    )_ \__;      ";"          :_ ;  \_\       `,','
    :__\  \    * `,'*         \  \  :  \   *  8`;'*  *
        `^'     \ :/           `^'  `-^-'   \v/ :  \/
```

**Comment by mandarvaze** [comment]
On gitter I was told that previous version (2.1.0) may work OK, but I doubt it.
I checked the "blame" for [this](https://github.com/ethereum/populus/blob/master/populus/cli/chain_cmd.py#L56) line - it hasn't changed in couple of years.

**Comment by mandarvaze** [comment]
Considering  #395 plans to remove `populus chain` command altogether, is it worth keeping this open/working to fix this ?

@pipermerriam Please comment.

**Comment by pipermerriam** [comment]
No, the entire `populus chain` and chain management in general is going to be removed.
